### PR TITLE
Dynamic messaging

### PR DESCRIPTION
**Pull request by himkak**
- Added DynamicMessage functionality, following the similar usage and implementation pattern as other IMessage implementations
  - To create 
`DynamicMessage dm = new DynamicMessage(desc);
            dm.Add("single_string", "sss");`
  - To serialize
`dm.WriteTo(outputStream);`
  - To deserialize
` deserializedDm = (DynamicMessage) dm.Parser.ParseFrom(inputStream)`
  - The descriptor could not be made static, as every instance of DynamicMessage can have a separate descriptor. So the parser is also non-static.
- Added support for unknown fields
- Added Unit tests
- Removed the workflow file
- Removed the Builder pattern from DynamicMessage

### CODE REVIEW

**Comment by jskeet** [comment]
This appears to be a diff from the previous PR, rather than from the current head of the main repo, which makes it harder to review. Please could you fix things up so that it's showing a diff against the main repo?

**Comment by himkak** [comment]
> This appears to be a diff from the previous PR, rather than from the current head of the main repo, which makes it harder to review. Please could you fix things up so that it's showing a diff against the main repo?

Fixed accordingly to show the appropriate differences.

**Comment by jskeet** [comment]
No, it still doesn't look right to me - if I look at the changes, it shows deleting a file that doesn't exist in the original repo.

**Comment by himkak** [comment]
Ok sure will do that, for that will have to merge this into my forked repo's main branch and the raise a PR from my forked repo main branch to protobuf original repo main branch.

**Review by dpk-srivastava — APPROVED** [review]

**Comment by himkak** [comment]
created a separate PR: https://github.com/protocolbuffers/protobuf/pull/11503
It shows the appropriate changes.

**Pull request merged**
